version: '2'

services:
  webapp:
    restart: always
    build: ./webapp
    expose:
      - "5000"
#    ports:
#      - "5000:5000"
#    command: /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:5000 run:app --reload --log-level DEBUG

  proxy:
    restart: always
    build: ./proxy
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - webapp