version: '2'

services:
  webapp:
    restart: always
    build: ./webapp
    expose:
      - "5000"

  proxy:
    restart: always
    build: ./proxy
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - webapp